volumes:
  db:
    driver: local

services:
  api-dev:
    build:
      target: development
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    command: npm run start:dev

  db:
    image: postgres:17.5-alpine3.22
    restart: always
    environment:
      - POSTGRES_DB=kuisine
      - POSTGRES_USER=kuisine
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    volumes:
      - ./pgadmin.json:/pgadmin4/servers.json
    ports:
      - '5050:80'
    depends_on:
      - db
